# Generated by Django 3.0.5 on 2020-04-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_value', models.DecimalField(decimal_places=10, max_digits=10)),
                ('y_value', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='surface_area',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
