# Generated by Django 3.0.5 on 2020-04-01 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200401_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='num_of_trees',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
