# Generated by Django 3.0.5 on 2020-04-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200401_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.Field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='num_of_trees',
            field=models.IntegerField(default=None),
        ),
    ]
