# Generated by Django 3.0.5 on 2020-04-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200402_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='x_value',
            field=models.DecimalField(decimal_places=10, max_digits=21),
        ),
    ]
