# Generated by Django 3.0.5 on 2020-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200402_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='world_x',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='world_y',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
